services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart:
      on-failure

  api:
    build:
      context: ./backend
      dockerfile: FileManagement.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=FileManagement;User Id=sa;Password=StrongPassw0rd!;TrustServerCertificate=True
      - Cloudinary__CloudName=dhghzuzbo
      - Cloudinary__ApiKey=458575585639673
      - Cloudinary__ApiSecret=tr1mp9rrOuJ3WLLQtwgFU5oQv0Y
    restart:
      on-failure
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassw0rd!
    ports:
      - "1433:1433"